
// Objective-C API for talking to the following Go packages
//
//	future
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Future_FRAMEWORK_H__
#define __Future_FRAMEWORK_H__

#include "Future.objc.h"
#include "Universe.objc.h"

#endif
